# Generated by Django 5.2.11 on 2026-02-10 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnsembleReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ensemble_type', models.CharField(choices=[('01', 'Temperature and Water Status (Low Power)'), ('11', 'Full Set (Temp, Water, 9-axis IMU, GPS)'), ('12', 'High Data Rate IMU')], max_length=2)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('water_status', models.CharField(blank=True, max_length=100, null=True)),
                ('geo_coordinates', models.CharField(blank=True, max_length=100, null=True)),
                ('imu_data', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='video/')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_video', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
