# Generated by Django 5.2.13 on 2026-05-02 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartfin_server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_session_id', models.CharField(max_length=100, unique=True)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='ensemblereading',
            name='session_id',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='ensembles', to='smartfin_server.session'),
            preserve_default=False,
        ),
    ]
