# Generated by Django 5.2.13 on 2026-05-16 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartfin_server', '0002_session_ensemblereading_session_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ensemblereading',
            old_name='session_id',
            new_name='session',
        ),
    ]
